version: "3"

services:
    rabbitmq:
        image: rabbitmq:${RABBITMQ_VERSION:-3.8}-management-alpine
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
        ports:
            - 15672:15672
        volumes:
            - ./enabled_plugins:/etc/rabbitmq/enabled_plugins